spring:
  application:
    name: service-monitor

server:
  port: 8080

app:
  monitoring:
    services:
      - name: "Google"
        url: "https://google.com"
      - name: "Local User Service"
        url: "http://localhost:8081/actuator/health"
      - name: "Local Order Service"
        url: "http://localhost:8082/actuator/health"